use utoipa::OpenApi;

/// Generated OpenAPI document for the Newton backend parity surface.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::health_check,
        crate::api::dashboard::list_products,
        crate::api::dashboard::list_components,
        crate::api::dashboard::list_pending_approvals,
        crate::api::dashboard::list_regressions,
        crate::api::dashboard::list_indicators,
        crate::api::dashboard::list_recent_actions,
        crate::api::portfolio::list_repos,
        crate::api::portfolio::list_repo_dependencies,
        crate::api::portfolio::list_module_dependencies,
        crate::api::portfolio::create_module_dependency,
        crate::api::portfolio::list_saved_views,
        crate::api::opportunities::list_opportunities,
        crate::api::opportunities::patch_opportunity,
        crate::api::requests::list_requests,
        crate::api::requests::create_request,
        crate::api::plans::list_plans,
        crate::api::plans::get_plan,
        crate::api::plans::approve_plan,
        crate::api::plans::reject_plan,
        crate::api::plans::list_executions,
        crate::api::workflows::list_workflows,
        crate::api::workflows::get_workflow,
        crate::api::workflows::create_workflow,
        crate::api::workflows::update_workflow,
        crate::api::workflows::update_node,
        crate::api::hil::list_hil_instances,
        crate::api::hil::list_hil_events,
        crate::api::hil::submit_hil_action,
        crate::api::operators::list_operators,
        crate::api::persistence::get_persistence,
        crate::api::persistence::put_persistence,
        crate::api::persistence::delete_persistence,
        crate::api::testing_reset::reset_testing
    ),
    components(schemas(
        crate::api::HealthResponse,
        newton_backend::ProductItem,
        newton_backend::ComponentItem,
        newton_backend::PendingApprovalItem,
        newton_backend::RegressionItem,
        newton_backend::IndicatorItem,
        newton_backend::RecentActionItem,
        newton_backend::RepoItem,
        newton_backend::RepoDependencyItem,
        newton_backend::ModuleRef,
        newton_backend::ModuleDependencyItem,
        newton_backend::CreateModuleDependencyBody,
        newton_backend::SavedViewItem,
        newton_backend::OpportunityItem,
        newton_backend::PatchOpportunityBody,
        newton_backend::RequestItem,
        newton_backend::CreateRequestBody,
        newton_backend::PlanItem,
        newton_backend::PlanSectionItem,
        newton_backend::PlanPolicyCheckItem,
        newton_backend::PlanApproverItem,
        newton_backend::PlanDetail,
        newton_backend::ExecutionItem,
        newton_backend::OperatorItem,
        newton_types::WorkflowInstance,
        newton_types::WorkflowStatus,
        newton_types::NodeState,
        newton_types::NodeStatus,
        newton_types::HilEvent,
        newton_types::HilEventType,
        newton_types::HilStatus,
        newton_types::OperatorDescriptor,
        newton_types::HilAction,
        newton_types::ApiError,
        crate::api::workflows::NodeUpdate,
        crate::api::workflows::WorkflowUpdateBody
    )),
    tags(
        (name = "health", description = "Service health and liveness endpoints"),
        (name = "dashboard", description = "Product, component, indicator, and activity aggregate endpoints"),
        (name = "portfolio", description = "Repository, module graph, and saved view endpoints"),
        (name = "opportunities", description = "Opportunity listing and state transition endpoints"),
        (name = "requests", description = "Change request intake endpoints"),
        (name = "plans", description = "Plan listing, detail, and approval workflow endpoints"),
        (name = "executions", description = "Execution record listing endpoints"),
        (name = "workflows", description = "Workflow runtime endpoints"),
        (name = "hil", description = "Human-in-the-loop event retrieval and action endpoints"),
        (name = "operators", description = "Operator catalog endpoint"),
        (name = "persistence", description = "Key-value persistence endpoints"),
        (name = "testing", description = "Test-only maintenance endpoints")
    ),
    info(
        title = "Newton Backend Parity API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Contract for Rust `newton serve` parity endpoints sourced from Rust DTOs and handlers."
    )
)]
pub struct ApiDoc;
