use utoipa::OpenApi;

/// Generated OpenAPI document for the Newton HTTP API.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::api::dashboard::list_products,
        crate::api::dashboard::list_components,
        crate::api::dashboard::list_pending_approvals,
        crate::api::dashboard::list_regressions,
        crate::api::dashboard::list_recent_actions,
        crate::api::portfolio::list_repos,
        crate::api::portfolio::list_repo_dependencies,
        crate::api::portfolio::list_module_dependencies,
        crate::api::portfolio::create_module_dependency,
        crate::api::portfolio::list_saved_views,
        crate::api::findings::list_findings,
        crate::api::findings::create_finding,
        crate::api::findings::get_finding,
        crate::api::findings::patch_finding,
        crate::api::findings::unblock_finding,
        crate::api::optimize_run::list_optimize_runs,
        crate::api::optimize_run::get_optimize_run,
        crate::api::optimize_run::get_optimize_run_trajectory,
        crate::api::optimize_run::list_optimize_cycles,
        crate::api::change_requests::list_change_requests,
        crate::api::change_requests::create_change_request,
        crate::api::change_requests::get_change_request,
        crate::api::change_requests::patch_change_request,
        crate::api::plans::list_plans,
        crate::api::plans::get_plan,
        crate::api::plans::approve_plan,
        crate::api::plans::reject_plan,
        crate::api::plans::list_executions,
        crate::api::workflows::list_workflows,
        crate::api::workflows::get_workflow,
        crate::api::workflows::create_workflow,
        crate::api::workflows::update_workflow,
        crate::api::workflows::update_node,
        crate::api::hil::list_hil_instances,
        crate::api::hil::list_hil_events,
        crate::api::hil::submit_hil_action,
        crate::api::operators::list_operators,
        crate::api::persistence::get_persistence,
        crate::api::persistence::put_persistence,
        crate::api::persistence::delete_persistence,
        crate::api::workflow_files::list_workflow_files,
        crate::api::workflow_files::get_workflow_file,
        crate::api::workflow_files::put_workflow_file,
        crate::api::workflow_files::delete_workflow_file,
        crate::api::workflow_files::validate_workflow_file,
        crate::api::catalog::get_product,
        crate::api::catalog::create_product,
        crate::api::catalog::put_product,
        crate::api::catalog::patch_product,
        crate::api::catalog::delete_product,
        crate::api::catalog::get_component,
        crate::api::catalog::create_component,
        crate::api::catalog::put_component,
        crate::api::catalog::patch_component,
        crate::api::catalog::delete_component,
        crate::api::catalog::get_repo,
        crate::api::catalog::create_repo,
        crate::api::catalog::put_repo,
        crate::api::catalog::patch_repo,
        crate::api::catalog::delete_repo,
        crate::api::catalog::list_modules,
        crate::api::catalog::get_module,
        crate::api::catalog::create_module,
        crate::api::catalog::put_module,
        crate::api::catalog::patch_module,
        crate::api::catalog::delete_module,
        crate::api::catalog::get_module_dependency,
        crate::api::catalog::patch_module_dependency,
        crate::api::catalog::delete_module_dependency,
        crate::api::catalog::list_kpis,
        crate::api::catalog::get_kpi,
        crate::api::catalog::create_kpi,
        crate::api::catalog::create_eval_run,
        crate::api::catalog::list_eval_runs,
        crate::api::catalog::get_eval_run,
        crate::api::catalog::list_eval_run_grades,
        crate::api::catalog::list_grades,
        crate::api::catalog::create_grade,
        crate::api::catalog::get_grade
    ),
    components(schemas(
        newton_types::ProductItem,
        newton_types::ComponentItem,
        newton_types::PendingApprovalItem,
        newton_types::RegressionItem,
        newton_types::KpiItem,
        newton_types::EvalRunItem,
        newton_types::CreateEvalRunBody,
        newton_types::RecentActionItem,
        newton_types::RepoItem,
        newton_types::RepoDependencyItem,
        newton_types::ModuleRef,
        newton_types::ModuleDependencyItem,
        newton_types::CreateModuleDependencyBody,
        newton_types::SavedViewItem,
        newton_types::FindingItem,
        newton_types::CreateFindingBody,
        newton_types::PatchFindingBody,
        newton_types::FindingStatus,
        newton_types::Severity,
        newton_types::Origin,
        newton_types::ChangeRequestItem,
        newton_types::CreateChangeRequestBody,
        newton_types::PatchChangeRequestBody,
        newton_types::PlanItem,
        newton_types::PlanSectionItem,
        newton_types::PlanPolicyCheckItem,
        newton_types::PlanApproverItem,
        newton_types::PlanDetail,
        newton_types::ExecutionItem,
        newton_types::OperatorItem,
        newton_types::ModuleItem,
        newton_types::DeletedItem,
        newton_types::CreateProductBody,
        newton_types::PutProductBody,
        newton_types::PatchProductBody,
        newton_types::CreateComponentBody,
        newton_types::PutComponentBody,
        newton_types::PatchComponentBody,
        newton_types::CreateRepoBody,
        newton_types::PutRepoBody,
        newton_types::PatchRepoBody,
        newton_types::CreateModuleBody,
        newton_types::PutModuleBody,
        newton_types::PatchModuleBody,
        newton_types::PatchModuleDependencyBody,
        newton_types::GradeItem,
        newton_types::CreateGradeBody,
        newton_types::CreateKpiBody,
        newton_types::CreateGradeInlineBody,
        newton_types::OptimizeRunItem,
        newton_types::OptimizeRunDetail,
        newton_types::OptimizeRunTrajectory,
        newton_types::OptimizeCycleItem,
        newton_types::WorkflowInstance,
        newton_types::WorkflowStatus,
        newton_types::NodeState,
        newton_types::NodeStatus,
        newton_types::HilEvent,
        newton_types::HilEventType,
        newton_types::HilStatus,
        newton_types::OperatorDescriptor,
        newton_types::HilAction,
        newton_types::ApiError,
        crate::api::workflows::NodeUpdate,
        crate::api::workflows::WorkflowUpdateBody,
        crate::api::workflow_files::WorkflowFileSummary,
        crate::api::workflow_files::WorkflowFileDetail,
        crate::api::workflow_files::PutWorkflowFileBody,
        crate::api::workflow_files::WorkflowFileDiagnostics,
        crate::api::workflow_files::LintFinding
    )),
    tags(
        (name = "dashboard", description = "Product, component, KPI, and activity aggregate endpoints"),
        (name = "portfolio", description = "Repository, module graph, and saved view endpoints"),
        (name = "findings", description = "Finding listing, creation, and state transition endpoints"),
        (name = "change-requests", description = "Change request intake and management endpoints"),
        (name = "plans", description = "Plan listing, detail, and approval workflow endpoints"),
        (name = "executions", description = "Execution record listing endpoints"),
        (name = "workflows", description = "Workflow runtime endpoints"),
        (name = "hil", description = "Human-in-the-loop event retrieval and action endpoints"),
        (name = "operators", description = "Operator catalog endpoint"),
        (name = "persistence", description = "Key-value persistence endpoints"),
        (name = "catalog", description = "Catalog entity CRUD endpoints"),
        (name = "workflow-files", description = "Workflow definition file CRUD endpoints"),
        (name = "optimize", description = "Optimization loop run and cycle endpoints")
    ),
    servers((url = "/api/v1")),
    info(
        title = "Newton API",
        version = env!("CARGO_PKG_VERSION"),
        description = "HTTP API served by `newton serve`."
    ),
    external_docs(
        url = "./newton-realtime.asyncapi.yaml",
        description = "Realtime (WebSocket + SSE) contract — AsyncAPI 3.0"
    )
)]
pub struct ApiDoc;
