# generated by datamodel-codegen:
#   filename:  workflow.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel, conint


class ArtifactCleanupPolicy(StrEnum):
    """
    Artifact cleanup policy.
    """

    lru = 'lru'


class ArtifactStorageSettings(BaseModel):
    """
    Artifact storage configuration embedded in workflow settings.
    """

    base_path: str
    cleanup_policy: ArtifactCleanupPolicy
    max_artifact_bytes: conint(ge=0)
    max_inline_bytes: conint(ge=0)
    max_total_bytes: conint(ge=0)
    retention_hours: conint(ge=0)


class CheckpointSettings(BaseModel):
    """
    Checkpointing configuration embedded in workflow settings.
    """

    checkpoint_enabled: bool
    checkpoint_interval_seconds: conint(ge=0)
    checkpoint_keep_history: bool
    checkpoint_on_task_complete: bool


class CommandOperatorSettings(BaseModel):
    """
    Command operator specific settings embedded in workflow settings.
    """

    allow_shell: bool


class Condition1(BaseModel):
    """
    Condition used to guard transitions between tasks.
    """

    field_expr: str = Field(..., alias='$expr')


class Condition(RootModel[Condition1 | bool]):
    root: Condition1 | bool = Field(
        ..., description='Condition used to guard transitions between tasks.'
    )


class ContextFidelity(StrEnum):
    """
    Context fidelity policy for agent operators (schema-only; not yet implemented).
    """

    full = 'full'
    summary = 'summary'
    truncate = 'truncate'


class GoalGateFailureBehavior(StrEnum):
    """
    Controls whether a reached-but-failed goal gate causes the workflow to fail.
    """

    fail = 'fail'
    allow = 'allow'


class HumanSettings(BaseModel):
    """
    Human interaction configuration for workflows.
    """

    audit_path: str
    default_timeout_seconds: conint(ge=0)


class IoBlock(BaseModel):
    """
    Workflow-level I/O contract block (optional).
    """

    error_schema: Any | None = None
    input_schema: Any | None = None
    output_schema: Any | None = None
    result_map: dict[str, Any] | None = None


class IoSettings(BaseModel):
    """
    Sub-settings for workflow I/O contract.
    """

    max_input_bytes: conint(ge=0) | None = None
    max_output_bytes: conint(ge=0) | None = None


class MacroInvocation(BaseModel):
    """
    Invocation of a named macro from the workflow task list.
    """

    macro: str
    with_: dict[str, Any] | None = Field({}, alias='with')


class ModelStylesheet(BaseModel):
    """
    Workflow-level model configuration for agent operators.
    """

    context_fidelity: ContextFidelity | None = Field(
        'summary',
        description='Conversation history retention policy.\nSchema-only in 017-h — does not affect prompt construction or operator behavior.',
    )
    model: str = Field(
        ..., description='Model identifier (e.g. "gpt-4o", "claude-sonnet-4-6").'
    )


class RedactionSettings(BaseModel):
    """
    Redaction configuration embedded in workflow settings.
    """

    redact_keys: list[str] | None = ['token', 'password', 'secret']


class RetryPolicy(BaseModel):
    """
    Retry configuration for a task.
    """

    backoff_ms: conint(ge=0)
    backoff_multiplier: float | None = None
    jitter_ms: conint(ge=0) | None = None
    max_attempts: conint(ge=0)


class TerminalKind(StrEnum):
    """
    Terminal task kind — determines how the workflow outcome is affected by a terminal task.
    """

    success = 'success'
    failure = 'failure'


class Transition(BaseModel):
    """
    Transition between tasks.
    """

    include_if: Condition | None = None
    label: str | None = None
    priority: int | None = 100
    to: str
    when: Condition | None = None


class TriggerType(StrEnum):
    """
    Allowed trigger types for workflow graphs.
    """

    manual = 'manual'
    webhook = 'webhook'


class WebhookSettings(BaseModel):
    """
    Webhook server configuration embedded in workflow settings.
    """

    auth_token_env: str
    bind: str
    enabled: bool
    max_body_bytes: conint(ge=0)


class WorkflowMetadata(BaseModel):
    """
    Metadata embedded with a workflow document.
    """

    description: str | None = None
    name: str | None = None
    tags: list[str] | None = None


class Operator(StrEnum):
    AgentOperator = 'AgentOperator'
    AssertCompletedOperator = 'AssertCompletedOperator'
    ChangeRequestOperator = 'ChangeRequestOperator'
    CommandOperator = 'CommandOperator'
    GhOperator = 'GhOperator'
    GitOperator = 'GitOperator'
    GraderAgentOperator = 'GraderAgentOperator'
    GraderCommandOperator = 'GraderCommandOperator'
    HumanApprovalOperator = 'HumanApprovalOperator'
    HumanDecisionOperator = 'HumanDecisionOperator'
    NoOpOperator = 'NoOpOperator'
    ReadControlFileOperator = 'ReadControlFileOperator'
    ReconcileOperator = 'ReconcileOperator'
    SetContextOperator = 'SetContextOperator'
    WorkflowOperator = 'WorkflowOperator'
    barrier = 'barrier'


class WorkflowTask(BaseModel):
    """
    Task definition consumed by the workflow executor.
    """

    classes: list[str] | None = []
    goal_gate: bool | None = False
    goal_gate_group: str | None = None
    id: str
    include_if: Condition | None = None
    max_iterations: conint(ge=0) | None = None
    name: str | None = None
    operator: Operator
    parallel_group: str | None = None
    params: Any | None = {}
    retry: RetryPolicy | None = None
    terminal: TerminalKind | None = None
    timeout_ms: conint(ge=0) | None = None
    transitions: list[Transition] | None = Field([], validate_default=True)


class WorkflowTrigger(BaseModel):
    """
    Workflow trigger definition supporting manual and webhook workflows.
    """

    payload: Any | None = {}
    schema_version: str
    type: TriggerType


class CompletionSettings(BaseModel):
    """
    Completion policy configuration for workflow graphs.
    """

    goal_gate_failure_behavior: GoalGateFailureBehavior | None = 'fail'
    require_goal_gates: bool | None = True
    stop_on_terminal: bool | None = True
    success_requires_no_task_failures: bool | None = True


class MacroDefinition(BaseModel):
    """
    Reusable macro definition containing one or more task templates.
    """

    name: str
    tasks: list[WorkflowTask]


class TaskOrMacro(RootModel[WorkflowTask | MacroInvocation]):
    root: WorkflowTask | MacroInvocation = Field(
        ...,
        description='Workflow task entries can be concrete tasks or macro invocations pre-transform.',
    )


class WorkflowSettings(BaseModel):
    """
    Execution settings for a workflow graph.
    """

    allow_env_fn: bool | None = Field(
        False,
        description='Opt-in flag for the Rhai `env()` expression function (spec 074 S8).\n`env()` reads `std::env::var` at expression-eval time, which makes\nparam resolution environment-dependent and non-deterministic; it is\ntherefore disabled unless a workflow explicitly sets this to `true`.',
    )
    artifact_storage: ArtifactStorageSettings | None = Field(
        {
            'base_path': '.newton/artifacts',
            'cleanup_policy': 'lru',
            'max_artifact_bytes': 104857600,
            'max_inline_bytes': 65536,
            'max_total_bytes': 1073741824,
            'retention_hours': 168,
        },
        validate_default=True,
    )
    checkpoint: CheckpointSettings | None = Field(
        {
            'checkpoint_enabled': True,
            'checkpoint_interval_seconds': 30,
            'checkpoint_keep_history': False,
            'checkpoint_on_task_complete': True,
        },
        validate_default=True,
    )
    command_operator: CommandOperatorSettings | None = Field(
        {'allow_shell': False}, validate_default=True
    )
    completion: CompletionSettings | None = Field(
        {
            'goal_gate_failure_behavior': 'fail',
            'require_goal_gates': True,
            'stop_on_terminal': True,
            'success_requires_no_task_failures': True,
        },
        validate_default=True,
    )
    continue_on_error: bool | None = False
    default_engine: str | None = Field(
        None,
        description='Default coding engine for all agent operators in this workflow.',
    )
    entry_task: str | None = 'start'
    human: HumanSettings | None = Field(
        {'audit_path': '.newton/state/workflows', 'default_timeout_seconds': 86400},
        validate_default=True,
    )
    io: IoBlock | None = Field(
        None,
        description='Workflow I/O contract: input/output schemas and result mapping.',
    )
    io_settings: IoSettings | None = Field(
        None, description='Workflow I/O size limits.'
    )
    max_task_iterations: conint(ge=0) | None = 100
    max_time_seconds: conint(ge=0) | None = 3600
    max_workflow_iterations: conint(ge=0) | None = 1000
    model_stylesheet: ModelStylesheet | None = Field(
        None,
        description='Default model configuration for agent operators.\nAllowed and silently ignored when the workflow has no AgentOperator tasks.',
    )
    parallel_limit: conint(ge=0) | None = 1
    redaction: RedactionSettings | None = Field(
        {'redact_keys': ['token', 'password', 'secret']}, validate_default=True
    )
    required_triggers: list[str] | None = []
    stream_agent_stdout: bool | None = Field(
        False,
        description='Whether to stream agent engine stdout to the terminal by default.\nIndividual agent tasks can override this setting.',
    )
    webhook: WebhookSettings | None = Field(
        {
            'auth_token_env': 'NEWTON_WEBHOOK_TOKEN',
            'bind': '127.0.0.1:8787',
            'enabled': False,
            'max_body_bytes': 1048576,
        },
        validate_default=True,
    )


class WorkflowDefinition(BaseModel):
    """
    Workflow-level configuration.
    """

    context: Any | None = {}
    settings: WorkflowSettings
    tasks: list[TaskOrMacro]


class WorkflowDocument(BaseModel):
    """
    Root document for a workflow graph definition.
    """

    macros: list[MacroDefinition] | None = None
    metadata: WorkflowMetadata | None = None
    mode: str
    triggers: WorkflowTrigger | None = None
    version: str
    workflow: WorkflowDefinition
