openapi: 3.0.3
info:
  title: Newton Loop CLI API
  description: Command-line interface specification for Newton Loop optimization framework
  version: 1.0.0
  contact:
    name: Newton Loop Framework

servers:
  - url: 'newton'
    description: Newton Loop CLI binary

paths:
  /run:
    post:
      summary: Execute optimization loop on workspace
      description: Run complete evaluation-advice-execution cycles on a workspace until completion or resource limits
      operationId: runOptimization
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: string
            description: Path to workspace directory
        - name: max-iterations
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            description: Maximum number of optimization iterations
        - name: max-time
          in: query
          schema:
            type: integer
            default: 300
            minimum: 1
            description: Maximum execution time in seconds
        - name: evaluator-cmd
          in: query
          schema:
            type: string
            description: Command to run for evaluation phase (enables strict mode)
        - name: advisor-cmd
          in: query
          schema:
            type: string
            description: Command to run for advice phase (enables strict mode)
        - name: executor-cmd
          in: query
          schema:
            type: string
            description: Command to run for execution phase (enables strict mode)
        - name: evaluator-status-file
          in: query
          schema:
            type: string
            default: "artifacts/evaluator_status.md"
            description: Path to evaluator status output file
        - name: advisor-recommendations-file
          in: query
          schema:
            type: string
            default: "artifacts/advisor_recommendations.md"
            description: Path to advisor recommendations output file
        - name: executor-log-file
          in: query
          schema:
            type: string
            default: "artifacts/executor_log.md"
            description: Path to executor log output file
        - name: tool-timeout-seconds
          in: query
          schema:
            type: integer
            default: 30
            minimum: 1
            description: Global timeout for tool execution in seconds
        - name: evaluator-timeout
          in: query
          schema:
            type: integer
            minimum: 1
            description: Specific timeout for evaluator tool
        - name: advisor-timeout
          in: query
          schema:
            type: integer
            minimum: 1
            description: Specific timeout for advisor tool
        - name: executor-timeout
          in: query
          schema:
            type: integer
            minimum: 1
            description: Specific timeout for executor tool
      responses:
        '0':
          description: Success - optimization completed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✅ Optimization completed successfully
                  Execution ID: abc123-def456
                  Status: completed
                  Iterations completed: 5
                  Final score: 0.85
                  Duration: 45.2 seconds
                  Completed at: 2026-01-19T10:30:00Z
        '1':
          description: Error - optimization failed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✗ Optimization failed
                  Error ID: err789-ghi012
                  Error Category: ToolFailure
                  Error Severity: High

  /step:
    post:
      summary: Execute single optimization iteration cycle
      description: Run one complete evaluation-advice-execution cycle
      operationId: runSingleStep
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: string
            description: Path to workspace directory
        - name: execution-id
          in: query
          schema:
            type: string
            description: Optional execution ID for tracking
      responses:
        '0':
          description: Success - step completed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✓ Single step execution completed successfully
                  Execution ID: abc123-def456
                  Execution State: running
                  Iterations Completed: 3
                  Elapsed Time: 25.3s
        '1':
          description: Error - step failed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✗ Single step execution failed
                  Error: Tool execution timeout

  /status:
    get:
      summary: Check optimization execution status
      description: Get current status of an optimization execution
      operationId: getExecutionStatus
      parameters:
        - name: execution-id
          in: query
          required: true
          schema:
            type: string
            description: ID of the optimization execution
        - name: workspace
          in: query
          schema:
            type: string
            default: "."
            description: Workspace path
      responses:
        '0':
          description: Success - status retrieved
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Execution Status: running
                  Current Iteration: 3
                  Elapsed Time: 45.2s
                  Estimated Remaining Time: 120.5s

                  Performance Metrics:
                    Iterations/Second: 0.15
                    Average Iteration Time: 6.67s
                    Completed Iterations: 3
                    Failed Iterations: 0
        '1':
          description: Error - execution not found or invalid
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✗ Execution not found

  /report:
    get:
      summary: Generate optimization summary report
      description: Generate detailed optimization results report
      operationId: generateReport
      parameters:
        - name: execution-id
          in: query
          required: true
          schema:
            type: string
            description: ID of the optimization execution
        - name: workspace
          in: query
          schema:
            type: string
            default: "."
            description: Workspace path
        - name: format
          in: query
          schema:
            type: string
            enum: [text, json]
            default: text
            description: Report output format
      responses:
        '0':
          description: Success - report generated
          content:
            text/plain:
              schema:
                type: string
                example: |
                  OPTIMIZATION REPORT
                  ===================

                  Execution ID: abc123-def456

                  BEST SOLUTION
                  -------------
                  Solution ID: sol001
                  Iteration: 5
                  Score: 0.92
                  Validation Status: valid
            application/json:
              schema:
                type: object
                properties:
                  execution_id:
                    type: string
                  best_solution:
                    type: object
                  optimization_summary:
                    type: object
        '1':
          description: Error - execution not found or not completed
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ✗ Execution not completed

components:
  schemas:
    ExecutionResult:
      type: object
      properties:
        execution_completed:
          type: boolean
        execution_id:
          type: string
        status:
          type: string
          enum: [completed, failed, terminated]
        iterations_completed:
          type: integer
        final_score:
          type: number
          nullable: true
        duration_seconds:
          type: number
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true

    ErrorReport:
      type: object
      properties:
        error_id:
          type: string
        error_timestamp:
          type: string
          format: date-time
        error_category:
          type: string
        error_severity:
          type: string
        error_message:
          type: string
        error_context:
          type: object
        error_details:
          type: object
          properties:
            component_id:
              type: string
            error_code:
              type: string
            stack_trace:
              type: string
            recovery_status:
              type: string
        recovery_suggestions:
          type: array
          items:
            type: string