//! Core Newton domain models, configuration, and orchestration utilities that drive workspace executions.
pub mod batch_config;
pub mod config;
pub mod context;
pub mod entities;
pub mod error;
pub mod git;
pub mod history_recorder;
pub mod logger;
pub mod orchestrator;
pub mod performance;
pub mod results_processor;
pub mod success_policy;
pub mod template;
pub mod tool_executor;
pub mod types;
pub mod workspace;

pub use crate::tools::ToolResult;
pub use batch_config::{find_workspace_root, parse_conf, BatchProjectConfig};
pub use config::{ConfigLoader, ConfigValidator, NewtonConfig};
pub use context::ContextManager;
pub use entities::{ArtifactMetadata, OptimizationExecution};
pub use error::{AppError, DefaultErrorReporter, ErrorReporter};
pub use git::{BranchManager, CommitManager, GitManager, PullRequestManager};
pub use history_recorder::ExecutionHistoryRecorder;
pub use orchestrator::OptimizationOrchestrator;
pub use performance::PerformanceProfiler;
pub use results_processor::{OutputFormat, ResultsProcessor};
pub use success_policy::SuccessPolicy;
pub use template::{TemplateInfo, TemplateManager, TemplateRenderer};
pub use types::*;
